bastion:
  hosts:
    "bastion-1":
      "ansible_host": "172.232.159.90"
      "ansible_user": "root"
    
controlplane:
  hosts:
    "plane-1":
      "ansible_host": "192.168.0.2"
      "ansible_user": "root"
    "plane-2":
      "ansible_host": "192.168.0.3"
      "ansible_user": "root"
    "plane-3":
      "ansible_host": "192.168.0.4"
      "ansible_user": "root"
    
worker:
  hosts:
    "worker-1":
      "ansible_host": "192.168.0.10"
      "ansible_user": "root"
    "worker-2":
      "ansible_host": "192.168.0.11"
      "ansible_user": "root"
    "worker-3":
      "ansible_host": "192.168.0.12"
      "ansible_user": "root"
    
cluster:
  children:
    controlplane:
    worker:
  vars:
    ansible_ssh_common_args: '-o ProxyJump="root@172.232.159.90"'

all:
  children:
    bastion:
    controlplane:
    worker:
