name: Reusable action for building and publishing application artifacts
description: Builds and publishes application artifacts

inputs:
  service-name:
    description: The name of the service to build a docker image from
    required: true

  version:
    description: The version of the application to publish
    required: true

  registry-username:
    description: The username to use for authenticating against the container registry
    required: true

  registry-password:
    description: The password to use for authenticating against the container registry
    required: true

runs:
  using: composite
  steps:
    - name: Set up docker
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push container image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: services/${{ inputs.service-name }}/Dockerfile
        push: true
        tags: |
          ghcr.io/thedatasnok/idata2502-project-${{ inputs.service-name }}:${{ github.ref_name }}
