name: Reusable action for building and publishing application artifacts
description: Builds and publishes application artifacts

inputs:
  version:
    description: The version of the application to publish
    required: true

  registry-username:
    description: The username to use for authenticating against the container registry
    required: true

  registry-password:
    description: The password to use for authenticating against the container registry
    required: true

runs:
  using: composite
  steps:
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2

    - name: Log in to container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-password }}

    - name: Build java artifacts
      shell: bash
      run: gradle jib
