name: Deploy environment
description: Reusable action for deploying the application to a given environment

inputs:
  environment:
    description: The name of the environment to deploy to
    required: true
  kubeconfig:
    description: The kubeconfig to use to connect to the cluster
    required: true
  github-token:
    description: The GitHub token to use for installing Helm without being rate limited
    required: true
  hostname:
    description: The hostname to deploy to
    required: true
  cluster-issuer:
    description: The cluster issuer to use for ingress TLS certificates
    required: true
  tag:
    description: The tag to use for finding candidate images
    required: true

runs:
  using: composite
  steps:
    - uses: azure/setup-kubectl@v3

    - uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ inputs.kubeconfig }}

    - uses: azure/setup-helm@v3
      with:
        token: ${{ inputs.github-token }}

    - name: Add target namespace
      shell: bash
      run: |
        kubectl apply --insecure-skip-tls-verify -f - <<EOF
        apiVersion: hnc.x-k8s.io/v1alpha2
        kind: SubnamespaceAnchor
        metadata:
          namespace: idata-org
          name: ${{ inputs.environment }}
        EOF

    - run: |
        helm upgrade ${{ inputs.environment }} ./helm \
          --install \
          --namespace ${{ inputs.environment }} \
          --set hostname=${{ inputs.hostname }} \
          --set clusterIssuer=${{ inputs.cluster-issuer }} \
          --set version=${{ inputs.tag }}
      shell: bash
