---
k3s_agent:
  with-node-id: true
  node-ip: "{{ hostvars[inventory_hostname]['private_ip'] | default('') }}"
  node-external-ip: "{{ hostvars[inventory_hostname]['public_ip'] | default('') }}"
  node-label:
    - "worker"
