---
- name: Set node hostnames
  hosts: cluster
  become: true
  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

- name: Extract IP addresses
  hosts: cluster
  gather_facts: true
  tasks:
    - name: Set private IP address
      ansible.builtin.set_fact:
        private_ip: "{{ item }}"
      loop: "{{ ansible_all_ipv4_addresses | default([]) }}"
      when: not item.startswith('192.168.0') and item.startswith('192.168')

    - name: Set public IP address
      ansible.builtin.set_fact:
        public_ip: "{{ item }}"
      loop: "{{ ansible_all_ipv4_addresses | default([]) }}"
      when: not item.startswith('192.168') and public_ip is not defined

- name: Install cluster
  hosts: cluster
  become: true
  vars_files:
    - ../vars.yml
  roles:
    - name: Install k3s
      role: xanmanning.k3s
      vars:
        k3s_state: installed
