---
- name: Bastion host SSH key scan
  hosts: bastion
  gather_facts: false
  tasks:
    - name: Scan bastion host
      delegate_to: localhost
      changed_when: false
      register: bastion_keys
      ansible.builtin.command: ssh-keyscan -H {{ ansible_host }}

    - name: Add bastion to known hosts
      delegate_to: localhost
      ansible.builtin.known_hosts:
        state: present
        path: /home/github/.ssh/known_hosts
        name: '{{ ansible_host }}'
        key: '{{ bastion_keys.stdout_lines | join("\n") }}'

- name: Cluster hosts SSH key scan
  gather_facts: false
  hosts: cluster
  tasks:
    - name: Scan cluster hosts
      changed_when: false
      delegate_to: localhost
      register: cluster_keys
      vars:
        jump_user: "{{ hostvars['bastion-1']['ansible_user'] }}"
        jump_host: "{{ hostvars['bastion-1']['ansible_host'] }}"
      ansible.builtin.command: ssh {{ jump_user }}@{{ jump_host }} "ssh-keyscan -H {{ ansible_host }}"

    - name: Add cluster hosts to known hosts
      delegate_to: localhost
      ansible.builtin.known_hosts:
        state: present
        path: /home/github/.ssh/known_hosts
        name: '{{ ansible_host }}'
        key: '{{ cluster_keys.stdout_lines | join("\n") }}'
