---
- name: SSH key scan
  hosts: localhost
  tasks:
    - name: Create known_hosts file
      ansible.builtin.file:
        path: ~/.ssh/known_hosts
        state: touch
        mode: '0700'

    - name: Scan bastion host
      changed_when: 1 == 2
      loop: "{{ groups['bastion'] }}"
      when: item != 'localhost'
      ansible.builtin.command: ssh-keyscan -H {{ hostvars[item]['ansible_host'] }} >> ~/.ssh/known_hosts

    - name: Scan cluster hosts
      changed_when: 1 == 2
      loop: "{{ groups['cluster'] }}"
      when: item != 'localhost'
      vars:
        jump_user: "{{ hostvars['bastion-1']['ansible_user'] }}"
        jump_host: "{{ hostvars['bastion-1']['ansible_host'] }}"
      ansible.builtin.command: ssh {{ jump_user }}@{{ jump_host }} "ssh-keyscan -H {{ hostvars[item]['ansible_host'] }}" >> ~/.ssh/known_hosts
