---
k3s_control_node: true
k3s_etcd_datastore: true

k3s_server:
  node-ip: "{{ ansible_eth1.ipv4.address }}"
  tls-san:
    - "{{ k3s_registration_address }}"
  advertise-address: "{{ ansible_eth1.ipv4.address }}"
  bind-address: 0.0.0.0
  write-kubeconfig-mode: 644
  node-external-ip: "{{ ansible_eth1.ipv4.address }}"
  disable:
    - traefik
    - servicelb

k3s_server_manifests_urls:
  - url: https://raw.githubusercontent.com/metallb/metallb/v0.13.12/config/manifests/metallb-native.yaml
    filename: metallb.yml
  - url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/baremetal/deploy.yaml
    filename: ingress-nginx.yml

k3s_server_manifests_templates:
  - external-dns.yml.j2
  - lets-encrypt.yml.j2
  - api-server-ingress.yml.j2
  - dashboard-ingress.yml.j2
