---
- name: Read vault secrets
  ansible.builtin.uri:
    url: "{{ hcp_vault_url_base }}/open"
    method: GET
    headers:
      Authorization: "Bearer {{ hcp_auth.json.access_token }}"
      Content-Type: "application/json"
  register: hcp_vault_secrets

- name: Parse vault secrets
  ansible.builtin.set_fact:
    remote_vault: "{{ hcp_vault_secrets.json.secrets | json_query('[].{key: name, value: version.value}') | items2dict }}"
