---
- name: Create new secret
  ansible.builtin.uri:
    url: "{{ hcp_vault_url_base }}/kv"
    method: POST
    headers:
      Authorization: "Bearer {{ hcp_auth.json.access_token }}"
      Content-Type: "application/json"
    body_format: json
    body: "{{ request_body }}"
