name: Continuous integration

on:
  push:
    branches:
      - main
    paths:
      - services/backend/**
      - services/frontend/**
  pull_request:
    branches:
      - main
    paths:
      - services/backend/**
      - services/frontend/**
  workflow_call:

jobs:
  lint_backend:
    name: Lint backend service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Lint backend
        run: bun lint:backend

  lint_frontend:
    name: Lint frontend service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Lint frontend
        run: bun lint:frontend

  test_backend:
    name: Test backend service
    runs-on: ubuntu-latest
    needs:
      - lint_backend
    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
    env:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Prepare database
        working-directory: services/backend
        run: bun db:migrate

      - name: Test backend
        working-directory: services/backend
        run: bun test

  test_frontend:
    name: Test frontend project
    runs-on: ubuntu-latest
    needs:
      - lint_frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Test frontend
        working-directory: services/frontend
        run: bun test
