name: Continuous integration

on:
  push:
    branches:
      - main
    paths:
      - services/backend/**
      - services/frontend/**
  pull_request:
    branches:
      - main
    paths:
      - services/backend/**
      - services/frontend/**

jobs:
  test_backend:
    name: Test backend service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Test backend
        working-directory: services/backend
        run: bun test

  test_frontend:
    name: Test frontend project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Test frontend
        working-directory: services/frontend
        run: bun test

  test_e2e:
    name: End-to-end tests
    runs-on: ubuntu-latest
    needs:
      - test_backend
      - test_frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Test e2e
        working-directory: services/e2e
        run: bun test

  build_artifacts:
    name: Build artifacts
    runs-on: ubuntu-latest
    needs:
      - test_e2e
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up docker
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
