name: Continuous integration

on:
  push:
    branches:
      - main
    paths:
      - services/backend/**
      - services/frontend/**
  pull_request:
    branches:
      - main
    paths:
      - services/backend/**
      - services/frontend/**

jobs:
  test_backend:
    name: Test backend service
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
    env:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Prepare database
        working-directory: services/backend
        run: bun db:migrate

      - name: Test backend
        working-directory: services/backend
        run: bun test

  test_frontend:
    name: Test frontend project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Test frontend
        working-directory: services/frontend
        run: bun test

  test_e2e:
    name: End-to-end tests
    runs-on: ubuntu-latest
    # disabled
    if: 1 == 2
    needs:
      - test_backend
      - test_frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Install playwright browsers
        working-directory: services/e2e
        run: bunx playwright install --with-deps

      - name: Run playwright tests
        working-directory: services/e2e
        run: bunx playwright test

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: services/e2e/playwright-report/
          retention-days: 30

  build_artifacts:
    name: Build artifacts
    runs-on: ubuntu-latest
    if: 1 == 2
    needs:
      - test_backend
      - test_frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up docker
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
