name: Continuous integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_infrastructure:
    name: Lint infrastructure code
    runs-on: ubuntu-latest

  lint_configuration:
    name: Lint configuration code
    runs-on: ubuntu-latest
