name: Deploy production environment

on:
  push:
    tags:
      - "*"
    branches:
      - main
    paths:
      - services/backend/**
      - services/frontend/**
  workflow_dispatch:

jobs:
  continuous_integration:
    name: CI
    uses: ./.github/workflows/ci.yaml

  build_artifacts:
    name: Build artifacts
    runs-on: ubuntu-latest
    needs:
      - continuous_integration
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up docker
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend container image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: services/backend/Dockerfile
          push: true
          tags: |
            ghcr.io/thedatasnok/idata2502-project-backend:${{ github.ref }}
            ghcr.io/thedatasnok/idata2502-project-backend:latest

      - name: Build and push backend container image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: services/frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/thedatasnok/idata2502-project-frontend:${{ github.ref }}
            ghcr.io/thedatasnok/idata2502-project-frontend:latest

  check_infrastructure_ready:
    name: Check if infrastructure is ready
    runs-on: ubuntu-latest
    steps:
      - name: Attempt a HTTP request to K8S api
        run: |
          if curl -s --fail ${{ env.K8S_URL }} -o /dev/null; then
            echo "Cluster API is responding"
          else
            echo "Cluster API did not respond, aborting the workflow."
            exit 1
          fi

  deploy_staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    environment: staging
    needs:
      - build_artifacts
      - check_infrastructure_ready
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  deploy_production:
    name: Deploy to production
    needs: deploy_staging
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
