name: Deploy infrastructure

on:
  push:
    branches:
      - main
    paths:
      - "infrastructure/**"
      - "!infrastructure/README.md"

jobs:
  lint_infrastructure:
    name: Lint infrastructure definitions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.   }}

      - name: Check formatting
        working-directory: ./infrastructure/definition
        run: terraform fmt -check

      - name: Initialize terraform
        working-directory: ./infrastructure/definition
        run: terraform init

      - name: Validate definitions
        working-directory: ./infrastructure/definition
        run: terraform validate -no-color

  apply_infrastructure:
    name: Apply infrastructure definitions
    runs-on: ubuntu-latest
    needs: lint_infrastructure
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Initialize terraform
        working-directory: ./infrastructure/definition
        run: terraform init

  lint_configuration:
    name: Lint configuration code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ./infrastructure/configuration

      - name: Run ansible lint
        uses: ansible/ansible-lint@v6

  apply_configuration:
    name: Apply configuration
    runs-on: ubuntu-latest
    needs:
      - lint_configuration
      - apply_infrastructure
    defaults:
      run:
        working-directory: ./infrastructure/configuration

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Prepare venv
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Prepare vault secret
        working-directory: ./infrastructure/configuration
        env:
          VAULT_SECRET: ${{ secrets.ANSIBLE_VAULT_SECRET }}
        run: echo $VAULT_SECRET > vault_pass.txt

      - name: Run install cluster playbook
        working-directory: ./infrastructure/configuration
        run: ansible-playbook playbooks/install-cluster.yml -i inventory/hosts.yml --vault-id prod@vault_pass.txt

      - name: Update account token
        working-directory: ./infrastructure/configuration
        run: ansible-playbook playbooks/github-pipeline-secret.yml -i inventory/hosts.yml
