name: Deploy infrastructure

on:
  push:
    branches:
      - main

jobs:
  lint_infrastructure:
    name: Lint infrastructure definitions
    runs-on: ubuntu-latest

  apply_infrastructure:
    name: Apply infrastructure definitions
    runs-on: ubuntu-latest
    needs: lint_infrastructure

  lint_configuration:
    name: Lint configuration code
    runs-on: ubuntu-latest

  apply_configuration:
    name: Apply configuration
    runs-on: ubuntu-latest
    needs:
      - lint_configuration
      - apply_infrastructure
